### ISSUE TITLE
Get json

### ISSUE THREAD

**Issue by Qnetis** [OndrejNepozitek/ProceduralLevelGenerator#56]
get json.
Hello, this is the best generator I've seen.
There is a problem, I can't get the global coordinates of each room in json.
I can't find a place where in the room.Shape add room.Position.
Can you help with this please?

**Comment by Qnetis** [comment]
It turned out to be easy to write your own json. The library is clear and everything is accessible.

**Comment by OndrejNepozitek** [comment]
I'm glad you figured it out!
